
<div id="social">
	<div class="wrap">
		<div class="inner clearfix">
    		<div class="container">
				<ul id="social-links">
					<li class="social facebook"><a href="http://www.facebook.com/pages/Flowform-Ramps/1379875322233605" rel="external" title="facebook">facebook</a></li>
					<li class="social twitter"><a href="https://twitter.com/flowformramps" rel="external" title="twitter">twitter</a></li>
					<li class="social instagram"><a href="http://instagram.com/flowformramps" rel="external" title="instagram">instagram</a></li>
					<li class="social linkedin"><a href="http://www.linkedin.com/company/flowform-bike-ramps" rel="external" title="LinkedIn">LinkedIn</a></li>
					<li class="social youtube"><a href="http://www.youtube.com/channel/UCpLsMVRwuhGYdckkdBGweGQ" rel="external" title="YouTube">YouTube</a></li>
					<li class="phone">
						<div>
							<span class="archivo phone">1.800.539.0960</span><br />
							<span class="email"><a href="mailto:info@flowformramps.com"><strong>info@flowformramps.com</strong></a></span>
						</div>    
					</li>
            	</ul>
			</div>
		</div>
	</div>
</div>
