
<div id="buckets">
	<div class="wrap padding">
    	<div class="inner">
        
        	<ul class="nostyle layout-grid clearfix">
            	<li class="grid third">
                	<div class="inner">
                    	<a href=""><img src="/<?php print path_to_theme() ?>/images/bucket_catalogue.jpg" /></a>
                    </div>
                </li>
                <li class="grid third">
                	<div class="inner">
                    	<a href=""><img src="/<?php print path_to_theme() ?>/images/bucket_project.jpg" /></a>
                    </div>
                </li>
                <li class="grid third">
                	<div class="inner">
                    	<a href=""><img src="/<?php print path_to_theme() ?>/images/bucket_video.jpg" /></a>
                    </div>
                </li>
            </ul>
        
        </div>
    </div>
</div>