
<div id="social">
	<div class="wrap">
		<div class="inner">
    
            <ul id="social-links">
                <li class="social facebook"><a href="" rel="external" title="facebook">facebook</a></li>
                <li class="social twitter"><a href="" rel="external" title="twitter">twitter</a></li>
                <li class="social instagram"><a href="" rel="external" title="instagram">instagram</a></li>
                <li class="social linkedin"><a href="" rel="external" title="LinkedIn">LinkedIn</a></li>
                <li class="social youtube"><a href="" rel="external" title="YouTube">YouTube</a></li>
                <li>
                    <div>
                        <span class="archivo phone">1.800.539.0960</span><br />
                        <span class="email"><a href="mailto:info@flowformramps.com"><strong>info@flowformramps.com</strong></a></span>
                    </div>    
                </li>
            </ul>

		</div>
	</div>
</div>
